db.url=jdbc:postgresql://localhost:5432/pool_conexiones
db.user=postgres
db.password=123456789

simulation.samples=5000
simulation.maxRetries=3
simulation.maxIterative=100

# AQUI ESTA EL ARREGLO DE LOS NOMBRES
db.query.select=SELECT 1
db.query.insert=INSERT INTO prueba(nombre, fecha) VALUES('test', NOW())
db.query.update=UPDATE prueba SET nombre = 'ejecutado' WHERE id = (SELECT max(id) FROM prueba)

# AQUI ESTAN LAS CONDICIONES DINAMICAS COMPLETAS
db.pool.minIdle=2
db.pool.maxSize=20