db.url=jdbc:postgresql://localhost:5432/pool_conexiones
db.user=postgres
db.password=123456789

simulation.samples=100
simulation.maxRetries=3
simulation.maxIterative=1000

query.select=SELECT 1
query.insert=INSERT INTO prueba(nombre, fecha) VALUES('test', NOW())
query.update=UPDATE prueba SET nombre = 'ejecutado' WHERE id = (SELECT max(id) FROM prueba)

db.pool.maxSize=20
db.pool.minIdle=5
db.pool.idleTimeout=30000
db.pool.connectionTimeout=20000