db.url=jdbc:postgresql://localhost:5432/postgres?ssl=false
db.user=postgres
db.password=31379406

simulation.samples=100
simulation.maxRetries=3
simulation.maxIterative=1000

query.select=SELECT 1
query.insert=INSERT INTO prueba(nombre, fecha) VALUES('test', NOW())
query.update=UPDATE prueba SET nombre = 'ejecutado' WHERE id = (SELECT max(id) FROM prueba)

db.pool.maxSize=20